[package]
name = "rets"
version = "0.1.0"
authors = ["Ajith Hussain <csy0013@googlemail.com>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
git2 = "0.8"
libgit2-sys = "0.7.11"
regex = "1"
chrono = "0.4"
